/**
 * SDG Airlines — Apps Script entry point.
 *
 * The Index/Quote/Arrival pages are generated by `python scripts/build_gas.py`
 * from docs/. Do not edit them here; every build overwrites them.
 */
function doGet(e) {
  var page = (e && e.parameter && e.parameter.page) || 'index';

  var pages = {
    index:   { file: 'Index',   title: 'SDG Airlines — Air cargo tools' },
    quote:   { file: 'Quote',   title: 'SDG Airlines — Rate quotation' },
    arrival: { file: 'Arrival', title: 'SDG Airlines — Arrival charges' }
  };

  // Keep the old published links working
  if (page === 'quoter') page = 'quote';
  if (page === 'calculator') page = 'arrival';

  var target = pages[page] || pages.index;

  return HtmlService.createHtmlOutputFromFile(target.file)
    .setTitle(target.title)
    .addMetaTag('viewport', 'width=device-width, initial-scale=1')
    .setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
}
